version: '3'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
